version: "3.7"
services:
  server:
    image: ludwigschubi/own-solid-server:latest
    restart: always
    ports:
      - 443:443
      - 80:80
      - 8080:8080
    volumes:
      - ./config/data:/usr/src/app/data
      - ./config/.db:/usr/src/app/.db
      - ./config/fullchain.pem:/usr/src/app/fullchain.pem
      - ./config/privkey.pem:/usr/src/app/privkey.pem
      - ./config/config.json:/usr/src/app/config.json